### ISSUE TITLE
Shareable URL

### ISSUE THREAD

**Issue by kumy** [GeoKretyMap/geokretymap.github.io#3]
Reported by mail:

That with each change in map center position and zoomlevel, the location
URL be updated with coordinates and zoom, in a way similar to Google
Maps, that use anchor data (#XXXX part of URL) for this purpose.

As such, the current view of the map can be easily shared with a simple
copy/paste or be kept as a bookmark.
Also settings such as layers and move age and status could also be saved
in the URL.

**Comment by andrixnet** [comment]
Location and zoom level: CONFIRMED. 
Layer: defaults to OSM
Geokrety moved more 90 days ago: CONFIRMED
Geokrety with unknown move date: CONFIRMED
Geokrety present in cache = off: CONFIRMED
Geokrety reported as missing: not tested. 

One problem still present: the map does not react to changes in the anchor part or the URL. 
The URL with #.... only works if opened in new window.
